# set tab width to 4 for prettier code.
set global tabstop 4
set global indentwidth 0

# change buffer-delete (bd) to match up with bn and bp, for the sake of my brain
alias global bd delete-buffer

unmap global normal c
map global normal c <a-i>

unmap global normal r
map global normal r c

map global normal <s-d> <a-d>

map global user y '<a-|>xsel -i -b<ret>'

#highlight matching brackets
add-highlighter global/ show-matching
set-face global MatchingChar rgb:8FBCBB,rgb:BF616A

#eventual command for ranger file chooser... This should probably just open ranger for file operations.
#The built in edit primitive in kakoune is actually super reasonable...
#def -docstring "Open a ranger session that will allow you to select a file
#for editing in kakoune
#" rangerfilechooser %{
#	eval terminal 'ranger; echo hello'
#}
